tour_button_css_s = "div.ng-scope:nth-child(3) div.main-container:nth-child(168) div.view-animate.ng-scope div.ng-scope div.container-fluid section.listing-image-overlay.overlay-dark.ng-scope:nth-child(3) div.listing-content article:nth-child(1) div.content-main div.half-page-div:nth-child(1) > a.rounded-text.dark-grey-border.white.moved-up-half.z-index-top.ng-scope"

explore_button_css_s = "div.MuiDialog-root:nth-child(3) div.MuiDialog-container.MuiDialog-scrollPaper:nth-child(3) div.MuiPaper-root.MuiDialog-paper.MuiDialog-paperScrollPaper.MuiDialog-paperWidthSm.MuiPaper-elevation24.MuiPaper-rounded div.MuiDialogContent-root.dialog-content form:nth-child(2) button.MuiButtonBase-root.MuiButton-root.MuiButton-contained.sign-in-button:nth-child(5) > span.MuiButton-label"
pop_button_css_s = "#cookie-ok-button"

spot_button_css_s = "pot_button"

door_button_css_s = "div.ng-scope:nth-child(3) div.main-container:nth-child(168) div.view-animate.ng-scope div.ng-scope div.container-fluid section.listing-image-overlay.overlay-top.overlay-dark:nth-child(2) div.listing-content article:nth-child(2) article:nth-child(1) div:nth-child(1) a.ng-scope:nth-child(1)"

email_field_css_s = "div.MuiDialog-root:nth-child(3) div.MuiDialog-container.MuiDialog-scrollPaper:nth-child(3) div.MuiPaper-root.MuiDialog-paper.MuiDialog-paperScrollPaper.MuiDialog-paperWidthSm.MuiPaper-elevation24.MuiPaper-rounded div.MuiDialogContent-root.dialog-content form:nth-child(2) div.MuiFormControl-root.MuiTextField-root.input:nth-child(1) div.MuiInputBase-root.MuiInput-root.MuiInput-underline.MuiInputBase-formControl.MuiInput-formControl > input.MuiInputBase-input.MuiInput-input.input-props-username"
pass_field_css_s= "div.MuiDialog-root:nth-child(3) div.MuiDialog-container.MuiDialog-scrollPaper:nth-child(3) div.MuiPaper-root.MuiDialog-paper.MuiDialog-paperScrollPaper.MuiDialog-paperWidthSm.MuiPaper-elevation24.MuiPaper-rounded div.MuiDialogContent-root.dialog-content form:nth-child(2) div.MuiFormControl-root.MuiTextField-root.input:nth-child(3) div.MuiInputBase-root.MuiInput-root.MuiInput-underline.MuiInputBase-formControl.MuiInput-formControl > input.MuiInputBase-input.MuiInput-input.input-props-password"